---
- hosts: all
  become: true
  tasks:

#  - name: install apache and php
#    package:
#      name:
#        - "{{ apache_package }}"
#        - "{{ php_package }}"
#      state: latest
#      update_cache: yes

#### Above script use variable which are mentioned in inventory file ####  

  - name: install apache2 package on Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php package on CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  
