---
- hosts: all
  become: true
  pre_tasks:
  
  - name: Upgrade all packages to latest version in all servers ( Ubuntu and CentOS )  
    package:
      name: '*'
      state: latest

#  - name: install updates (CentOS)
#    tags: always
#    dnf:
#      update_only: yes
#      update_cache: yes
#    when: ansible_distribution == "CentOS"

#  - name: install updates (Ubuntu)
#    tags: always
#    apt:
#      upgrade: dist
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

- hosts: workstation
  become: true
  tasks:
   
  - name: install unzip
    package:
      name: unzip
   
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package on Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

#  - name: Upgrade all packages to the latest version of Ubuntu
#    apt:
#      name: "*"
#      state: latest
#    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php package on CentOS servers
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS" 
  
  - name: firewalld open port 80 on CentOS
    firewalld:
      port: 80/tcp
      permanent: yes
      immediate: yes
      state: enabled
      zone: public
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf 
      regexp: '^ServerAdmin'
      line: ServerAdmin knaveen007singh@outlook.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed


#  - name: upgrade all packages to the latest version of CentOS
#    dnf:
#      name: "*"
#      state: latest
#    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"  

- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
