---
- hosts: all
  become: true
  pre_tasks:
  
  - name: Upgrade all packages & update repo index to latest version in all servers ( Ubuntu and CentOS )  
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true 
  roles: 
    - base

- hosts: workstation
  become: true
  roles:
    - workstation

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers


- hosts: file_servers
  become: true
  roles:
    - file_servers 

